#!/bin/bash

IPT="/sbin/iptables"

$IPT -F
$IPT -X
$IPT -t nat -F
$IPT -t nat -X
$IPT -t mangle -F
$IPT -t mangle -X

$IPT -P INPUT   DROP
$IPT -P FORWARD DROP
$IPT -P OUTPUT  ACCEPT

$IPT -A INPUT -i lo -j ACCEPT

$IPT -A INPUT -p udp -m state --state ESTABLISHED -j ACCEPT
$IPT -A INPUT -p tcp -m state --state ESTABLISHED -j ACCEPT

$IPT -A INPUT -p tcp -m multiport --dports {{ansible_port}},10050 -m state --state NEW,ESTABLISHED -j ACCEPT

$IPT -A INPUT -p icmp -m state --state ESTABLISHED,RELATED -j ACCEPT
